# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id_punch', models.IntegerField(primary_key=True, serialize=False)),
                ('fabula', models.CharField(max_length=200, null=True)),
                ('censure', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rapper',
            fields=[
                ('id_rapper', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=500)),
                ('photo', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id_season', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('photo', models.BinaryField(null=True)),
                ('grid', models.BinaryField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='punch',
            name='id_rapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main2.Rapper'),
        ),
        migrations.AddField(
            model_name='punch',
            name='id_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main2.Season'),
        ),
    ]
